// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqafgnmqyhkbndkemnxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxYWZnbm1xeWhrYm5ka2Vtbnh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MDcwNDgsImV4cCI6MjA3NzA4MzA0OH0.dENsOOXeaAdBnBmXLV1naf_wy00WmcnYppuDbMsLVIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});